import os
import time
import colorama
import sys
from colorama import Fore, Back, Style
from colorama import init, AnsiToWin32

def clear_screen():
    os.system("clear")

def display_text_with_delay(text):
    for char in text:
        print(char, end="", flush=True)
        time.sleep(0.05)
    print("\n")
    time.sleep(0.05)

def ram_tweaks_menu():
    while True:
        clear_screen()
        print("\033[0m")
        print(Fore.RED + "██████╗░░█████╗░███╗░░░███╗")
        print("██╔══██╗██╔══██╗████╗░████║")
        print("██████╔╝███████║██╔████╔██║")
        print("██╔══██╗██╔══██║██║╚██╔╝██║")
        print("██║░░██║██║░░██║██║░╚═╝░██║")
        print("╚═╝░░╚═╝╚═╝░░╚═╝╚═╝░░░░░╚═╝")
        print("\n████████╗░██╗░░░░░░░██╗███████╗░█████╗░██╗░░██╗")
        print("╚══██╔══╝░██║░░██╗░░██║██╔════╝██╔══██╗██║░██╔╝")
        print("░░░██║░░░░╚██╗████╗██╔╝█████╗░░███████║█████═╝░")
        print("░░░██║░░░░░████╔═████║░██╔══╝░░██╔══██║██╔═██╗░")
        print("░░░██║░░░░░╚██╔╝░╚██╔╝░███████╗██║░░██║██║░╚██╗")
        print("░░░╚═╝░░░░░░╚═╝░░░╚═╝░░╚══════╝╚═╝░░╚═╝╚═╝░░╚═╝")
        print (Fore.CYAN +"by caonhatthanh")
        print("\033[0m")

        print(Fore.GREEN +"[1] SUPER LIGHT \033[34m")
        print(Fore.GREEN +"[2] LIGHT \033[34m")
        print(Fore.GREEN +"[3] MEDIUM \033[34m")
        print(Fore.GREEN +"[4] HIGH \033[34m")
        print(Fore.GREEN +"[5] EXIT \033[33m")

        choice = input(Fore.MAGENTA +"\nTùy Chọn: ")

        if choice == "1":
            clear_screen()
            print("\033[1;33mBắt Đầu Khởi Chạy\n\033[0m")             
            display_text_with_delay("Force Stopping bellavita.toast")
            display_text_with_delay("Force Stopping ccc71.st.cpu")
            display_text_with_delay("Force Stopping ch.protonmail.android")
            display_text_with_delay("Force Stopping android")
            display_text_with_delay("Force Stopping android.auto_generated_rro_product__")
            display_text_with_delay("Force Stopping android.auto_generated_rro_vendor__")
            display_text_with_delay("Force Stopping android.autoinstalls.config.ANDROID")
            display_text_with_delay("Force Stopping bellavita.toast")
            display_text_with_delay("Force Stopping ConfigServices")
            display_text_with_delay("Force Stopping ccc71.st.cpu")
            display_text_with_delay("Force Stopping ch.chrome")
            display_text_with_delay("Force Stopping co.sitic.pp")
            display_text_with_delay("Force Stopping com.GOOGLE.SERVICES")
            input("Nhấn Enter Để Tiếp Tục...")
        elif choice == "2":
            clear_screen()
            print("\033[1;33mBắt Đầu Khởi Chạy\n\033[0m")
            display_text_with_delay("Force Stopping bellavita.toast")
            display_text_with_delay("Force Stopping bellavita.toast")
            display_text_with_delay("Force Stopping ccc71.st.cpu")
            display_text_with_delay("Force Stopping ch.mail.android")
            display_text_with_delay("Force Stopping android")
            display_text_with_delay("Force Stopping android.auto_generated_rro_product")
            display_text_with_delay("Force Stopping android.auto_generated_rro_vendor")
            display_text_with_delay("Force Stopping android.autoinstalls.config.ANDROID")
            display_text_with_delay("Force Stopping com.android.cameraextensions")
            display_text_with_delay("Force Stopping com.android.carrierconfig")
            display_text_with_delay("Force Stopping com.android.carrierdefaultapp")
            display_text_with_delay("Force Stopping com.android.certinstaller")
            display_text_with_delay("Force Stopping com.android.chrome")
            display_text_with_delay("Force Stopping com.android.companiondevicemanager")
            display_text_with_delay("Force Stopping com.android.cts.ctsshim")
            display_text_with_delay("Force Stopping com.android.cts.priv.ctsshim")
            display_text_with_delay("Force Stopping com.android.dreams.basic")
            display_text_with_delay("Force Stopping com.android.dreams.phototable")
            display_text_with_delay("Force Stopping com.android.dynsystem")
            display_text_with_delay("Force Stopping com.android.egg")
            display_text_with_delay("Force Stopping com.android.externalstorage")
            display_text_with_delay("Force Stopping com.android.hotspot2.osulogin")
            display_text_with_delay("Force Stopping com.android.hotwordenrollment.okgoogle")
            display_text_with_delay("Force Stopping com.android.hotwordenrollment.xgoogle")
            display_text_with_delay("Force Stopping com.android.htmlviewer")
            display_text_with_delay("Force Stopping com.android.inputdevices")
            display_text_with_delay("Force Stopping com.android.internal.display.cutout.emulation.corner")
            display_text_with_delay("Force Stopping com.android.internal.display.cutout.emulation.double")
            display_text_with_delay("Force Stopping com.android.internal.display.cutout.emulation.hole")
            display_text_with_delay("Force Stopping com.android.internal.display.cutout.emulation.tall")
            display_text_with_delay("Force Stopping com.android.internal.display.cutout.emulation.waterfall")
            display_text_with_delay("Force Stopping com.android.internal.systemui.navbar.gestural")
            display_text_with_delay("Force Stopping com.android.internal.systemui.navbar.gestural_extra_wide_back")
            display_text_with_delay("Force Stopping com.android.internal.systemui.navbar.gestural_narrow_back")
            display_text_with_delay("Force Stopping com.android.internal.systemui.navbar.gestural_wide_back")
            display_text_with_delay("Force Stopping com.android.internal.systemui.navbar.threebutton")
            display_text_with_delay("Force Stopping com.android.internal.systemui.onehanded.gestural")
            display_text_with_delay("Force Stopping com.android.keychain")
            display_text_with_delay("Force Stopping com.android.localtransport")
            display_text_with_delay("Force Stopping com.android.location.fused")
            display_text_with_delay("Force Stopping com.android.managedprovisioning")
            display_text_with_delay("Force Stopping com.android.mms.service")
            display_text_with_delay("Force Stopping com.android.mtp")
            display_text_with_delay("Force Stopping com.android.nfc")
            display_text_with_delay("Force Stopping com.android.ons")
            display_text_with_delay("Force Stopping com.android.pacprocessor")
            display_text_with_delay("Force Stopping com.android.phone")
            display_text_with_delay("Force Stopping com.android.phone.auto_generated_rro_product__")
            display_text_with_delay("Force Stopping com.android.printspooler")
            display_text_with_delay("Force Stopping com.android.providers.blockednumber")
            display_text_with_delay("Force Stopping com.android.providers.calendar")
            display_text_with_delay("Force Stopping com.android.providers.downloads")
            display_text_with_delay("Force Stopping com.android.providers.downloads.ui")
            display_text_with_delay("Force Stopping com.android.providers.media")
            display_text_with_delay("Force Stopping com.android.providers.partnerbookmarks")
            display_text_with_delay("Force Stopping com.android.providers.settings")
            display_text_with_delay("Force Stopping com.android.providers.settings.auto_generated_rro_product__")
            input("Nhấn Enter Để Tiếp Tục...")
        elif choice == "3":
            clear_screen()
            print("\033[1;33mBắt Đầu Khởi Chạy\n\033[0m")
            display_text_with_delay("Force Stopping ch.protonmail.android")
            display_text_with_delay("Force Stopping android")
            display_text_with_delay("Force Stopping android.auto_generated_rro_product__")
            display_text_with_delay("Force Stopping android.auto_generated_rro_vendor__")
            display_text_with_delay("Force Stopping android.autoinstalls.config.ANDROID")
            display_text_with_delay("Force Stopping bellavita.toast")
            display_text_with_delay("Force Stopping by4a.setedit22")
            display_text_with_delay("Force Stopping  ccc71.st.cpu")
            display_text_with_delay("Force Stopping ch.protonmail.android")
            display_text_with_delay("Force Stopping co.sitic.pp")
            display_text_with_delay("Force skip Service com.Termux")
            display_text_with_delay("Force Stopping com.photos")
            display_text_with_delay("Force Stopping com.ဗိုင်းရပ်စ်အင်ဂျင် ")
            display_text_with_delay("Force Stopping com.android.apps.tag")
            display_text_with_delay("Force Stopping com.android.backupconfirm")
            display_text_with_delay("Force Stopping com.android.bips")
            display_text_with_delay("Force Stopping com.android.bluetooth")
            display_text_with_delay("Force Stopping com.android.bluetoothmidiservice")
            display_text_with_delay("Force Stopping com.android.bookmarkprovider")
            display_text_with_delay("Force Stopping com.android.calllogbackup")
            display_text_with_delay("Force Stopping com.android.cameraextensions")
            display_text_with_delay("Force Stopping com.android.carrierconfig")
            display_text_with_delay("Force Stopping com.android.carrierdefaultapp")
            display_text_with_delay("Force Stopping com.android.certinstaller")
            display_text_with_delay("Force Stopping com.android.chrome")
            display_text_with_delay("Force Stopping com.android.companiondevicemanager")
            display_text_with_delay("Force Stopping com.android.cts.ctsshim")
            display_text_with_delay("Force Stopping com.android.cts.priv.ctsshim")
            display_text_with_delay("Force Stopping com.android.dreams.basic")
            display_text_with_delay("Force Stopping com.android.dreams.phototable")
            display_text_with_delay("Force Stopping com.android.dynsystem")
            display_text_with_delay("Force Stopping com.android.egg")
            display_text_with_delay("Force Stopping com.android.externalstorage")
            display_text_with_delay("Force Stopping com.android.hotspot2.osulogin")
            display_text_with_delay("Force Stopping com.android.hotwordenrollment.okgoogle")
            display_text_with_delay("Force Stopping com.android.hotwordenrollment.xgoogle")
            display_text_with_delay("Force Stopping com.android.htmlviewer")
            display_text_with_delay("Force Stopping com.android.inputdevices")
            display_text_with_delay("Force Stopping com.android.internal.display.cutout.emulation.corner")
            display_text_with_delay("Force Stopping com.android.internal.display.cutout.emulation.double")
            display_text_with_delay("Force Stopping com.android.internal.display.cutout.emulation.hole")
            display_text_with_delay("Force Stopping com.android.internal.display.cutout.emulation.tall")
            display_text_with_delay("Force Stopping com.android.internal.display.cutout.emulation.waterfall")
            display_text_with_delay("Force Stopping com.android.internal.systemui.navbar.gestural")
            display_text_with_delay("Force Stopping com.android.internal.systemui.navbar.gestural_extra_wide_back")
            display_text_with_delay("Force Stopping com.android.internal.systemui.navbar.gestural_narrow_back")
            display_text_with_delay("Force Stopping com.android.internal.systemui.navbar.gestural_wide_back")
            display_text_with_delay("Force Stopping com.android.internal.systemui.navbar.threebutton")
            display_text_with_delay("Force Stopping com.android.internal.systemui.onehanded.gestural")
            display_text_with_delay("Force Stopping com.android.keychain")
            display_text_with_delay("Force Stopping com.android.localtransport")
            display_text_with_delay("Force Stopping com.android.location.fused")
            display_text_with_delay("Force Stopping com.android.managedprovisioning")
            display_text_with_delay("Force Stopping com.android.mms.service")
            display_text_with_delay("Force Stopping com.android.mtp")
            display_text_with_delay("Force Stopping com.android.nfc")
            display_text_with_delay("Force Stopping com.android.ons")
            display_text_with_delay("Force Stopping com.android.pacprocessor")
            display_text_with_delay("Force Stopping com.android.phone")
            display_text_with_delay("Force Stopping com.android.phone.auto_generated_rro_product__")
            display_text_with_delay("Force Stopping com.android.printspooler")
            display_text_with_delay("Force Stopping com.android.providers.blockednumber")
            display_text_with_delay("Force Stopping com.android.providers.calendar")
            display_text_with_delay("Force Stopping com.android.providers.downloads")
            display_text_with_delay("Force Stopping com.android.providers.downloads.ui")
            display_text_with_delay("Force Stopping com.android.providers.media")
            display_text_with_delay("Force Stopping com.android.providers.partnerbookmarks")
            display_text_with_delay("Force Stopping com.android.providers.settings")
            display_text_with_delay("Force Stopping com.android.providers.settings.auto_generated_rro_product__")
            MEMORY_TWEAKS = [
                "adb shell ram_tweaks 1",
                "adb shell ram_booster 1",
                "adb shell setprop debug.performance.memory_trim 1"
                "adb shell setprop debug.performance.memory_reclaim 1"
                "adb shell setprop debug.performance.memory_boost 1"
                "adb shell setprop debug.performance.memory_preload 1"
                "adb shell setprop debug.performance.memory_large_cache 1"
                "adb shell setprop debug.performance.memory_min_free_kbytes 8192"
                "adb shell setprop debug.performance.memory_swappiness 1"
                "adb shell setprop debug.performance.memory_governor 1"
                "adb shell setprop debug.performance.memory_low 1"
                "adb shell setprop debug.performance.memory_alloc_limit 512M"
                "adb shell setprop debug.performance.memory_reclaim_interval 5000"
                "adb shell setprop debug.performance.memory_reclaim_delay 5000"
                "adb shell setprop debug.performance.memory_low_threshold 30"
                "adb shell setprop debug.performance.memory_high_threshold 80"
                "adb shell setprop debug.performance.memory_full_threshold 95"
                "adb shell setprop debug.performance.memory_compact_on_fsync 1"
                "adb shell kill-all services"
                "adb shell kill all"
                "adb shell set-services 3"
                "adb shell kill-all-processes"
            ]
            for adb_command in MEMORY_TWEAKS:
                os.system(adb_command)
                input(f"Comando ejecutado: {adb_command}\nNhấn Enter Để Tiếp Tục...")

            os.system("adb shell input keyevent 26")

            os.system(adb_command)
            input(f"Comando ejecutado: {adb_command}\nNhấn Enter Để Tiếp Tục...")

            os.system("adb shell input keyevent 26")
        elif choice == "4":
            clear_screen()
            print("\035[1;33mBắt Đầu Khởi Chạy\n\033[0m")
            display_text_with_delay("Force Stopping bellavita.toast")
            display_text_with_delay("Force Stopping ccc71.st.cpu")
            display_text_with_delay("Force Stopping ch.mail.android")
            display_text_with_delay("Force Stopping android")
            display_text_with_delay("Force Stopping android.auto_generated_rro_product")
            display_text_with_delay("Force Stopping android.auto_generated_rro_vendor")
            display_text_with_delay("Force Stopping android.autoinstalls.config.ANDROID")
            display_text_with_delay("Force Stopping com.android.cameraextensions")
            display_text_with_delay("Force Stopping com.android.carrierconfig")
            display_text_with_delay("Force Stopping com.android.carrierdefaultapp")
            display_text_with_delay("Force Stopping com.android.certinstaller")
            display_text_with_delay("Force Stopping com.android.chrome")
            display_text_with_delay("Force Stopping com.android.companiondevicemanager")
            display_text_with_delay("Force Stopping com.android.cts.ctsshim")
            display_text_with_delay("Force Stopping com.android.cts.priv.ctsshim")
            display_text_with_delay("Force Stopping com.android.dreams.basic")
            display_text_with_delay("Force Stopping com.android.dreams.phototable")
            display_text_with_delay("Force Stopping com.android.dynsystem")
            display_text_with_delay("Force Stopping com.android.egg")
            display_text_with_delay("Force Stopping com.android.externalstorage")
            display_text_with_delay("Force Stopping com.android.hotspot2.osulogin")
            display_text_with_delay("Force Stopping com.android.hotwordenrollment.okgoogle")
            display_text_with_delay("Force Stopping com.android.hotwordenrollment.xgoogle")
            display_text_with_delay("Force Stopping com.android.htmlviewer")
            display_text_with_delay("Force Stopping com.android.inputdevices")
            display_text_with_delay("Force Stopping com.android.internal.display.cutout.emulation.corner")
            display_text_with_delay("Force Stopping com.android.internal.display.cutout.emulation.double")
            display_text_with_delay("Force Stopping com.android.internal.display.cutout.emulation.hole")
            display_text_with_delay("Force Stopping com.android.internal.display.cutout.emulation.tall")
            display_text_with_delay("Force Stopping com.android.internal.display.cutout.emulation.waterfall")
            display_text_with_delay("Force Stopping com.android.internal.systemui.navbar.gestural")
            display_text_with_delay("Force Stopping com.android.internal.systemui.navbar.gestural_extra_wide_back")
            display_text_with_delay("Force Stopping com.android.internal.systemui.navbar.gestural_narrow_back")
            display_text_with_delay("Force Stopping com.android.internal.systemui.navbar.gestural_wide_back")
            display_text_with_delay("Force Stopping com.android.internal.systemui.navbar.threebutton")
            display_text_with_delay("Force Stopping com.android.internal.systemui.onehanded.gestural")
            display_text_with_delay("Force Stopping com.android.keychain")
            display_text_with_delay("Force Stopping com.android.localtransport")
            display_text_with_delay("Force Stopping com.android.location.fused")
            display_text_with_delay("Force Stopping com.android.managedprovisioning")
            display_text_with_delay("Force Stopping com.android.mms.service")
            display_text_with_delay("Force Stopping com.android.mtp")
            display_text_with_delay("Force Stopping com.android.nfc")
            display_text_with_delay("Force Stopping com.android.ons")
            display_text_with_delay("Force Stopping com.android.pacprocessor")
            display_text_with_delay("Force Stopping com.android.phone")
            display_text_with_delay("Force Stopping com.android.phone.auto_generated_rro_product__")
            display_text_with_delay("Force Stopping com.android.printspooler")
            display_text_with_delay("Force Stopping com.android.providers.blockednumber")
            display_text_with_delay("Force Stopping com.android.providers.calendar")
            display_text_with_delay("Force Stopping com.android.providers.downloads")
            display_text_with_delay("Force Stopping com.android.providers.downloads.ui")
            display_text_with_delay("Force Stopping com.android.providers.media")
            display_text_with_delay("Force Stopping com.android.providers.partnerbookmarks")
            display_text_with_delay("Force Stopping com.android.providers.settings")
            display_text_with_delay("Force Stopping com.android.providers.settings.auto_generated_rro_product__")
            input("Nhấn Enter Để Tiếp Tục...")
        elif choice == "3+":
            clear_screen()
            print("\033[1;33mBắt Đầu Khởi Chạy\n\033[0m")
            display_text_with_delay("Force Stopping ccc71.st.cpu")
            display_text_with_delay("Force Stopping ch.protonmail.android")
            display_text_with_delay("Force Stopping android")
            display_text_with_delay("Force Stopping android.auto_generated_rro_product__")
            display_text_with_delay("Force Stopping android.auto_generated_rro_vendor__")
            display_text_with_delay("Force Stopping android.autoinstalls.config.ANDROID")
            display_text_with_delay("Force Stopping bellavita.toast")
            display_text_with_delay("Force Stopping by4a.setedit22")
            display_text_with_delay("Force Stopping  ccc71.st.cpu")
            display_text_with_delay("Force Stopping ch.protonmail.android")
            display_text_with_delay("Force Stopping co.sitic.pp")
            display_text_with_delay("Force skip Service com.Termux")
            display_text_with_delay("Force Stopping com.photos")
            display_text_with_delay("Force Stopping com.ဗိုင်းရပ်စ်အင်ဂျင် ")
            display_text_with_delay("Force Stopping com.android.apps.tag")
            display_text_with_delay("Force Stopping com.android.backupconfirm")
            display_text_with_delay("Force Stopping com.android.bips")
            display_text_with_delay("Force Stopping com.android.bluetooth")
            display_text_with_delay("Force Stopping com.android.bluetoothmidiservice")
            display_text_with_delay("Force Stopping com.android.bookmarkprovider")
            display_text_with_delay("Force Stopping com.android.calllogbackup")
            display_text_with_delay("Force Stopping com.android.cameraextensions")
            display_text_with_delay("Force Stopping com.android.carrierconfig")
            display_text_with_delay("Force Stopping com.android.carrierdefaultapp")
            display_text_with_delay("Force Stopping com.android.certinstaller")
            display_text_with_delay("Force Stopping com.android.chrome")
            display_text_with_delay("Force Stopping com.android.companiondevicemanager")
            display_text_with_delay("Force Stopping com.android.cts.ctsshim")
            display_text_with_delay("Force Stopping com.android.cts.priv.ctsshim")
            display_text_with_delay("Force Stopping com.android.dreams.basic")
            display_text_with_delay("Force Stopping com.android.dreams.phototable")
            display_text_with_delay("Force Stopping com.android.dynsystem")
            display_text_with_delay("Force Stopping com.android.egg")
            display_text_with_delay("Force Stopping com.android.externalstorage")
            display_text_with_delay("Force Stopping com.android.hotspot2.osulogin")
            display_text_with_delay("Force Stopping com.android.hotwordenrollment.okgoogle")
            display_text_with_delay("Force Stopping com.android.hotwordenrollment.xgoogle")
            display_text_with_delay("Force Stopping com.android.htmlviewer")
            display_text_with_delay("Force Stopping com.android.inputdevices")
            display_text_with_delay("Force Stopping com.android.internal.display.cutout.emulation.corner")
            display_text_with_delay("Force Stopping com.android.internal.display.cutout.emulation.double")
            display_text_with_delay("Force Stopping com.android.internal.display.cutout.emulation.hole")
            display_text_with_delay("Force Stopping com.android.internal.display.cutout.emulation.tall")
            display_text_with_delay("Force Stopping com.android.internal.display.cutout.emulation.waterfall")
            display_text_with_delay("Force Stopping com.android.internal.systemui.navbar.gestural")
            display_text_with_delay("Force Stopping com.android.internal.systemui.navbar.gestural_extra_wide_back")
            display_text_with_delay("Force Stopping com.android.internal.systemui.navbar.gestural_narrow_back")
            display_text_with_delay("Force Stopping com.android.internal.systemui.navbar.gestural_wide_back")
            display_text_with_delay("Force Stopping com.android.internal.systemui.navbar.threebutton")
            display_text_with_delay("Force Stopping com.android.internal.systemui.onehanded.gestural")
            display_text_with_delay("Force Stopping com.android.keychain")
            display_text_with_delay("Force Stopping com.android.localtransport")
            display_text_with_delay("Force Stopping com.android.location.fused")
            display_text_with_delay("Force Stopping com.android.managedprovisioning")
            display_text_with_delay("Force Stopping com.android.mms.service")
            display_text_with_delay("Force Stopping com.android.mtp")
            display_text_with_delay("Force Stopping com.android.nfc")
            display_text_with_delay("Force Stopping com.android.ons")
            display_text_with_delay("Force Stopping com.android.pacprocessor")
            display_text_with_delay("Force Stopping com.android.phone")
            display_text_with_delay("Force Stopping com.android.phone.auto_generated_rro_product__")
            display_text_with_delay("Force Stopping com.android.printspooler")
            display_text_with_delay("Force Stopping com.android.providers.blockednumber")
            display_text_with_delay("Force Stopping com.android.providers.calendar")
            display_text_with_delay("Force Stopping com.android.providers.downloads")
            display_text_with_delay("Force Stopping com.android.providers.downloads.ui")
            display_text_with_delay("Force Stopping com.android.providers.media")
            display_text_with_delay("Force Stopping com.android.providers.partnerbookmarks")
            display_text_with_delay("Force Stopping com.android.providers.settings")
            display_text_with_delay("Force Stopping com.android.providers.settings.auto_generated_rro_product")
            input("Nhấn Enter Để Tiếp Tục...")
        elif choice == "5":
            break

if __name__ == "__main__":
    ram_tweaks_menu()
